apiVersion: apps/v1
kind: Deployment
metadata:
  name: barcode-mrcnn-app-gpu
spec:
  selector:
    matchLabels:
      app: barcode-mrcnn-app-gpu
  replicas:  2
  template:
    metadata:
      labels:
        app: barcode-mrcnn-app-gpu
    spec:
      containers:
      - name: barcode-mrcnn-app-gpu-container
        image: sgscomlcontainer.azurecr.io/barcode_mrcnn_app_gpu:v20210825a
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: barcode-app-service
spec:
  type: LoadBalancer
  selector:
    app: barcode-mrcnn-app-gpu
  ports:
  - port: 9090